/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewOrderIdRouteImport } from './routes/review.$orderId'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as ApiWebhooksRetellRouteImport } from './routes/api/webhooks/retell'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewOrderIdRoute = ReviewOrderIdRouteImport.update({
  id: '/review/$orderId',
  path: '/review/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksRetellRoute = ApiWebhooksRetellRouteImport.update({
  id: '/api/webhooks/retell',
  path: '/api/webhooks/retell',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/review/$orderId': typeof ReviewOrderIdRoute
  '/api/webhooks/retell': typeof ApiWebhooksRetellRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/review/$orderId': typeof ReviewOrderIdRoute
  '/api/webhooks/retell': typeof ApiWebhooksRetellRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/review/$orderId': typeof ReviewOrderIdRoute
  '/api/webhooks/retell': typeof ApiWebhooksRetellRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/orders'
    | '/order-confirmation/$orderId'
    | '/review/$orderId'
    | '/api/webhooks/retell'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/orders'
    | '/order-confirmation/$orderId'
    | '/review/$orderId'
    | '/api/webhooks/retell'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/orders'
    | '/order-confirmation/$orderId'
    | '/review/$orderId'
    | '/api/webhooks/retell'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  OrdersRoute: typeof OrdersRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
  ReviewOrderIdRoute: typeof ReviewOrderIdRoute
  ApiWebhooksRetellRoute: typeof ApiWebhooksRetellRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$orderId': {
      id: '/review/$orderId'
      path: '/review/$orderId'
      fullPath: '/review/$orderId'
      preLoaderRoute: typeof ReviewOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/retell': {
      id: '/api/webhooks/retell'
      path: '/api/webhooks/retell'
      fullPath: '/api/webhooks/retell'
      preLoaderRoute: typeof ApiWebhooksRetellRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  OrdersRoute: OrdersRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
  ReviewOrderIdRoute: ReviewOrderIdRoute,
  ApiWebhooksRetellRoute: ApiWebhooksRetellRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
